apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  namespace: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: pedidos
        image: <SEU-USUARIO-DOCKERHUB>/pedidos-service:v1.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: loja-config
        - secretRef:
            name: loja-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"